export const DAILY_BRIEFING_VERSION = 'daily-briefing-v1'
export const BRIEFING_STATUSES = Object.freeze({ READY: 'READY', CAUTION: 'CAUTION', BLOCKED: 'BLOCKED', INSUFFICIENT_DATA: 'INSUFFICIENT_DATA', ERROR: 'ERROR' })
export const PRIORITY_LEVELS = Object.freeze({ CRITICAL: 'CRITICAL', HIGH: 'HIGH', MEDIUM: 'MEDIUM', LOW: 'LOW', INFORMATIONAL: 'INFORMATIONAL' })
