import { evaluatePaperPerformance } from '../../src/core/analytics/paperPerformanceAnalyticsEngine.js'
import { createEquityCurveEngine } from './equityCurveEngine.js'
import { DEFAULT_PAPER_PERFORMANCE_REVIEW_CONFIG } from './paperPerformanceReviewConfig.js'

export const PAPER_PERFORMANCE_REVIEW_VERSION='paper-performance-review-v1'
const round=(v,d=2)=>Number((Number(v)||0).toFixed(d));const average=v=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0
function outcome(record={}){const accounting=record.accountingStatus??record.accountingUpdate?.status??record.accountingUpdateSnapshot?.status;const pnl=Number(record.realizedPnl??record.accountingUpdate?.account?.realizedPnlDelta??record.accountingUpdateSnapshot?.account?.realizedPnlDelta);const filled=record.status==='SIMULATED_FILLED'||record.executionStatus==='simulated'||record.decisionGate?.execution==='filled';return {eligible:record.paperTradingOnly!==false&&record.paperTrading!==false&&filled&&['position_closed','position_reduced'].includes(accounting)&&Number.isFinite(pnl),pnl,accounting}}
function sampleStatus(n,c){return n<c.minimumSample?'INSUFFICIENT_SAMPLE':n<c.developingSample?'EARLY':n<c.establishedSample?'DEVELOPING':'ESTABLISHED'}
function streaks(values){let w=0,l=0,mw=0,ml=0;for(const v of values){if(v>0){w++;l=0;mw=Math.max(mw,w)}else if(v<0){l++;w=0;ml=Math.max(ml,l)}else{w=0;l=0}}return{consecutiveWins:mw,consecutiveLosses:ml}}
function metrics(records){const rows=records.map(r=>({pnl:outcome(r).pnl,returnPct:Number(r.returnPct),record:r}));const pnl=rows.map(x=>x.pnl);const wins=pnl.filter(x=>x>0),losses=pnl.filter(x=>x<0),zeros=pnl.filter(x=>x===0);const base=evaluatePaperPerformance(rows.map((x,i)=>({tradeId:x.record.id??`trade-${i}`,paperTrading:true,journalStatus:'recorded',fill:{},decisionGate:{execution:'filled',accounting:'updated'},realizedPnl:x.pnl})),{emitEvent:false,timestamp:'1970-01-01T00:00:00.000Z'}).metrics;const equity=pnl.reduce((a,x)=>(a.push(a[a.length-1]+x),a),[0]);let peak=equity[0],drawdowns=[];for(const x of equity){peak=Math.max(peak,x);drawdowns.push(peak===0?0:((peak-x)/Math.max(1,Math.abs(peak)))*100)}const maxDrawdown=createEquityCurveEngine().calculateMaxDrawdown(equity);const returns=rows.map(x=>x.returnPct).filter(Number.isFinite);const mean=average(returns);const volatility=returns.length>1?Math.sqrt(average(returns.map(x=>(x-mean)**2))):0;const downside=returns.filter(x=>x<0);const downsideDev=downside.length?Math.sqrt(average(downside.map(x=>x*x))):0;return{totalCompletedTrades:pnl.length,winningTrades:wins.length,losingTrades:losses.length,breakevenTrades:zeros.length,winRate:round(pnl.length?wins.length/pnl.length*100:0),lossRate:round(pnl.length?losses.length/pnl.length*100:0),averageWin:round(average(wins)),averageLoss:round(average(losses)),winLossRatio:round(losses.length&&average(losses)!==0?average(wins)/Math.abs(average(losses)):0),expectancyPerTrade:round(base.expectancy),grossProfit:round(wins.reduce((a,b)=>a+b,0)),grossLoss:round(Math.abs(losses.reduce((a,b)=>a+b,0))),netRealizedPnl:round(base.netRealizedPnl),profitFactor:base.profitFactor,largestWin:base.largestWin,largestLoss:base.largestLoss,...streaks(pnl),maximumDrawdownPct:maxDrawdown,averageDrawdownPct:round(average(drawdowns)),recoveryFactor:round(maxDrawdown>0?base.netRealizedPnl/maxDrawdown:0),averageTradeReturn:round(mean),returnVolatility:round(volatility),sharpeStyle:returns.length>=5&&volatility>0?round(mean/volatility):null,sortinoStyle:returns.length>=5&&downsideDev>0?round(mean/downsideDev):null}}
function group(records,key,label,c){const map=new Map;for(const r of records){const value=key(r);if(value==null||value===''||value==='UNKNOWN')continue;const a=map.get(String(value))??[];a.push(r);map.set(String(value),a)}return [...map].sort(([a],[b])=>a.localeCompare(b)).map(([value,rows])=>rows.length<c.minimumGroupSample?{dimension:label,value,sampleSize:rows.length,status:'INSUFFICIENT_SAMPLE'}:{dimension:label,value,sampleSize:rows.length,status:sampleStatus(rows.length,c),performance:metrics(rows)})}
function trend(records,c){if(records.length<c.minimumSample)return'INSUFFICIENT_DATA';const recent=records.slice(-Math.min(c.recentWindow,records.length));const baseline=records.slice(0,-recent.length);if(!baseline.length)return'STABLE';const a=metrics(recent).expectancyPerTrade,b=metrics(baseline).expectancyPerTrade,scale=Math.max(1,Math.abs(b));if((a-b)/scale*100>=c.improvementPct)return'IMPROVING';if((b-a)/scale*100>=c.deteriorationPct)return'DETERIORATING';return'STABLE'}
function status(m,s,recent,c,coverage){if(s==='INSUFFICIENT_SAMPLE')return'INSUFFICIENT_SAMPLE';if(coverage<80)return'UNDER_REVIEW';if(m.maximumDrawdownPct>=c.degradedDrawdownPct||m.profitFactor<c.cautionProfitFactor)return'DEGRADED';if(recent==='DETERIORATING'||m.maximumDrawdownPct>=c.cautionDrawdownPct||m.expectancyPerTrade<=0)return'CAUTION';if(m.profitFactor>=c.healthyProfitFactor&&m.expectancyPerTrade>0)return'HEALTHY';return'UNDER_REVIEW'}
export function reviewPaperPerformance(records=[],options={}){const c=options.config??DEFAULT_PAPER_PERFORMANCE_REVIEW_CONFIG,asOf=options.asOf??new Date().toISOString();const sorted=[...(Array.isArray(records)?records:[])].sort((a,b)=>Date.parse(a.closedAt??a.simulatedAt??a.timestamp)-Date.parse(b.closedAt??b.simulatedAt??b.timestamp)||String(a.id??a.evaluationId).localeCompare(String(b.id??b.evaluationId)));const completed=sorted.filter(r=>outcome(r).eligible);const excluded=sorted.filter(r=>!outcome(r).eligible);const m=metrics(completed),sample=sampleStatus(completed.length,c),recentTrend=trend(completed,c),coverage=sorted.length?round(completed.length/sorted.length*100):0,reviewStatus=status(m,sample,recentTrend,c,coverage);const grouping=[['strategies',r=>r.strategyId,'strategyId'],['qualityBands',r=>r.tradeQuality?.band??r.qualityBand,'qualityBand'],['qualityScoreRanges',r=>{const x=Number(r.tradeQuality?.score??r.qualityScore);return Number.isFinite(x)?x>=90?'90-100':x>=80?'80-89':x>=70?'70-79':x>=55?'55-69':'0-54':null},'qualityScoreRange'],['trendRegimes',r=>r.regime?.trendRegime,'trendRegime'],['volatilityRegimes',r=>r.regime?.volatilityRegime,'volatilityRegime'],['riskRegimes',r=>r.regime?.riskRegime,'riskRegime'],['evaluationStatuses',r=>r.evaluationStatus,'evaluationStatus'],['symbols',r=>r.symbol,'symbol'],['assetTypes',r=>r.assetType??r.orderPlan?.assetType,'assetType'],['months',r=>String(r.closedAt??r.simulatedAt??'').slice(0,7),'month']];const feedback=[];if(sample==='INSUFFICIENT_SAMPLE')feedback.push('Insufficient sample; continue paper observation.');else{if(m.expectancyPerTrade>0&&m.maximumDrawdownPct<c.cautionDrawdownPct)feedback.push('Positive expectancy with controlled drawdown.');if(recentTrend==='DETERIORATING')feedback.push('Strategy results have deteriorated over the recent window.');if(m.maximumDrawdownPct>=c.cautionDrawdownPct)feedback.push('Recent drawdown is elevated.')}return{version:PAPER_PERFORMANCE_REVIEW_VERSION,status:reviewStatus,asOf,sample:{status:sample,completedTrades:m.totalCompletedTrades,wins:m.winningTrades,losses:m.losingTrades,breakeven:m.breakevenTrades},performance:m,recentTrend,feedback,coverage:{percentage:coverage,totalRecords:sorted.length,completed:completed.length,excluded:excluded.length,missingLinkage:excluded.filter(r=>r.status==='SIMULATED_FILLED').length,excludedByState:excluded.reduce((a,r)=>{const k=r.status??'INCOMPLETE';a[k]=(a[k]??0)+1;return a},{})},...Object.fromEntries(grouping.map(([name,key,label])=>[name,group(completed,key,label,c)])),boundaries:{paperTradingOnly:true,advisoryOnly:true,automaticStrategyChanges:false,automaticExecution:false}}
}
