import { describe, expect, it } from 'vitest'
import { buildMarketContextRegistry } from '../lib/market/context/marketContextRegistry.js'
import { buildAtlasMarketContext, buildSectorLeadership, buildSectorParticipation } from '../lib/market/context/marketContextEngine.js'

const candles = (start, end, count = 220, symbol = 'SPY') => Array.from({ length: count }, (_, index) => { const close = start + ((end - start) * index / (count - 1)); return { timestamp: new Date(Date.UTC(2025, 0, 1) + index * 86400000).toISOString(), open: close, high: close + 1, low: close - 1, close, volume: 1000, source: 'twelvedata', symbol } })
describe('Market Context', () => {
  it('builds a deterministic bounded governed ETF registry and rejects duplicates', () => { expect(buildMarketContextRegistry().entries).toHaveLength(14); expect(() => buildMarketContextRegistry({ entries: [{ symbol: 'SPY', enabled: true }, { symbol: 'SPY', enabled: true }] })).toThrow('market context registry is invalid') })
  it('ranks leading and lagging sectors deterministically against SPY', () => { const leadership = buildSectorLeadership({ candleSets: { SPY: candles(100, 110), XLK: candles(100, 160), XLF: candles(100, 80) }, generatedAt: '2026-08-27T00:00:00.000Z' }); expect(leadership.leaders[0].symbol).toBe('XLK'); expect(leadership.laggards[0].symbol).toBe('XLF'); expect(leadership.sectors.find((entry) => entry.symbol === 'XLK').relativeToSpy20).toBeGreaterThan(0) })
  it('labels partial coverage as an ETF proxy rather than true exchange breadth', () => { const leadership = buildSectorLeadership({ candleSets: { SPY: candles(100, 110), XLK: candles(100, 130) } }); const participation = buildSectorParticipation({ leadership }); expect(participation.status).toBe('INSUFFICIENT_DATA'); expect(participation.labels.display).toBe('SECTOR ETF PARTICIPATION PROXY'); expect(participation.boundaries.trueExchangeBreadthAvailable).toBe(false) })
  it('keeps unmapped candidate sector evidence unavailable', () => { const context = buildAtlasMarketContext({ candleSets: { SPY: candles(100, 110) }, selectedSymbol: 'AAPL', selectedCandles: candles(100, 115, 220, 'AAPL') }); expect(context.selectedCandidateContext.sectorProxySymbol).toBeNull(); expect(context.selectedCandidateContext.sectorRelativeStrength).toBe('UNAVAILABLE'); expect(context.boundaries.strategyOrRankingAuthority).toBe(false) })
})