import{describe,expect,it,vi}from'vitest';import{reviewPaperPerformance}from'../lib/analytics/paperPerformanceReview.js';import{createPaperPerformanceReviewHandler}from'../netlify/functions/paper-performance-review.js'
const at=i=>`2026-08-${String(i+1).padStart(2,'0')}T12:00:00.000Z`;function trade(pnl,i=0,extra={}){return{id:`t${i}`,status:'SIMULATED_FILLED',symbol:extra.symbol??'AAPL',strategyId:extra.strategyId??'momentum',assetType:'equity',simulatedAt:at(i),accountingStatus:'position_closed',realizedPnl:pnl,returnPct:extra.returnPct??pnl/100,tradeQuality:{score:extra.score??85,band:extra.band??'STRONG'},regime:{trendRegime:extra.trend??'BULL',volatilityRegime:extra.volatility??'NORMAL_VOLATILITY',riskRegime:extra.risk??'RISK_ON'},evaluationStatus:'APPROVED_FOR_PAPER_REVIEW',paperTradingOnly:true,...extra}}
describe('paper performance review',()=>{
 it('returns insufficient sample with no completed trades',()=>{const r=reviewPaperPerformance([],{asOf:at(20)});expect(r.status).toBe('INSUFFICIENT_SAMPLE');expect(r.sample.completedTrades).toBe(0)})
 it('calculates wins losses breakeven and core metrics',()=>{const r=reviewPaperPerformance([100,-50,0,200,-100].map(trade),{asOf:at(20)});expect(r.sample).toMatchObject({wins:2,losses:2,breakeven:1});expect(r.performance).toMatchObject({winRate:40,lossRate:40,averageWin:150,averageLoss:-75,expectancyPerTrade:30,grossProfit:300,grossLoss:150,netRealizedPnl:150,profitFactor:2,largestWin:200,largestLoss:-100})})
 it('calculates streaks drawdown recovery and returns without annualization',()=>{const r=reviewPaperPerformance([100,50,-25,-30,10].map((x,i)=>trade(x,i)),{asOf:at(20)});expect(r.performance.consecutiveWins).toBe(2);expect(r.performance.consecutiveLosses).toBe(2);expect(r.performance.maximumDrawdownPct).toBeGreaterThan(0);expect(r.performance.recoveryFactor).toBeGreaterThan(0);expect(r.performance.returnVolatility).toBeGreaterThan(0);expect(r.performance.sharpeStyle).not.toBeNull()})
 it.each([[Array(10).fill(0).map((_,i)=>trade(i<5?10:40,i)),'IMPROVING'],[Array(10).fill(0).map((_,i)=>trade(10,i)),'STABLE'],[Array(10).fill(0).map((_,i)=>trade(i<5?40:-10,i)),'DETERIORATING']])('detects recent trend', (rows,expected)=>expect(reviewPaperPerformance(rows,{asOf:at(20),config:{minimumSample:5,developingSample:20,establishedSample:50,minimumGroupSample:3,recentWindow:5,deteriorationPct:20,improvementPct:20,cautionDrawdownPct:10,degradedDrawdownPct:20,healthyProfitFactor:1.2,cautionProfitFactor:.9}}).recentTrend).toBe(expected))
 it('groups strategy quality regime symbol asset and month',()=>{const rows=Array.from({length:6},(_,i)=>trade(i%2?20:-5,i,{strategyId:i<3?'momentum':'breakout',band:i<3?'STRONG':'QUALIFIED',trend:i<3?'BULL':'RANGE'}));const r=reviewPaperPerformance(rows,{asOf:at(20)});expect(r.strategies).toHaveLength(2);expect(r.qualityBands).toHaveLength(2);expect(r.trendRegimes).toHaveLength(2);expect(r.assetTypes[0].value).toBe('equity');expect(r.months[0].value).toBe('2026-08')})
 it('suppresses metrics for tiny groups',()=>{const r=reviewPaperPerformance([trade(10,0,{symbol:'AAPL'}),trade(10,1,{symbol:'MSFT'}),trade(10,2,{symbol:'NVDA'}),trade(10,3),trade(10,4)],{asOf:at(20)});expect(r.symbols.find(x=>x.value==='MSFT').status).toBe('INSUFFICIENT_SAMPLE');expect(r.symbols.find(x=>x.value==='MSFT').performance).toBeUndefined()})
 it('excludes rejected nonfilled open and incomplete records',()=>{const valid=trade(10);const rows=[valid,{...trade(20,1),status:'SIMULATION_REJECTED'},{...trade(20,2),accountingStatus:'position_created'},{...trade(20,3),realizedPnl:undefined}];const r=reviewPaperPerformance(rows,{asOf:at(20)});expect(r.sample.completedTrades).toBe(1);expect(r.coverage.excluded).toBe(3)})
 it('is stable and has immutable advisory boundaries',()=>{const rows=[1,2,3,4,5].map(trade);expect(reviewPaperPerformance(rows,{asOf:at(20)})).toEqual(reviewPaperPerformance(rows,{asOf:at(20)}));expect(reviewPaperPerformance(rows,{asOf:at(20)}).boundaries).toEqual({paperTradingOnly:true,advisoryOnly:true,automaticStrategyChanges:false,automaticExecution:false})})
 it('has no provider AI mutation risk or execution dependency',()=>{const call=vi.fn();reviewPaperPerformance([trade(10)],{provider:call,ai:call,strategyMutation:call,riskMutation:call,orderExecution:call,asOf:at(20)});expect(call).not.toHaveBeenCalled()})
})
describe('paper performance endpoint',()=>{it('requires authentication',async()=>{const handler=createPaperPerformanceReviewHandler();const response=await handler({httpMethod:'GET',headers:{},queryStringParameters:{organizationId:'org-atlas-local'}});expect(response.statusCode).toBe(401)});it('uses tenant-scoped repository input',async()=>{const listExecutions=vi.fn(async()=>[]);const handler=createPaperPerformanceReviewHandler({ledgerRepository:{persistenceMode:'postgresql',listExecutions},authProvider:{authenticate:async()=>({ok:true,user:{id:'user-a',status:'active'},session:{id:'s',userId:'user-a',status:'active',expiresAt:'2099-01-01T00:00:00Z'}})},authorizationService:{assert:()=>({allowed:true})},organizationMembershipRepository:{getMembership:async()=>({organizationId:'org-a',userId:'user-a',role:'viewer',status:'active'})}});const response=await handler({httpMethod:'GET',headers:{authorization:'Bearer x'},queryStringParameters:{organizationId:'org-a',accountId:'paper-portfolio'}});expect(response.statusCode).toBe(200);expect(listExecutions).toHaveBeenCalledWith(expect.objectContaining({tenantContext:expect.objectContaining({organizationId:'org-a'}),userId:'user-a'}))})})
