import{describe,expect,it,vi}from'vitest';import{buildPaperLearningEvidence}from'../lib/analytics/paperLearning/index.js';import{createPaperLearningHandler}from'../netlify/functions/paper-learning.js'
const perf=(expectancy=10,pf=1.5)=>({totalCompletedTrades:10,winRate:60,expectancyPerTrade:expectancy,profitFactor:pf,netRealizedPnl:expectancy*10,averageTradeReturn:1,maxDrawdownPct:4,maximumDrawdownPct:4,recoveryFactor:2});const group=(value,sampleSize=10,expectancy=10,pf=1.5,status='EARLY')=>({value,sampleSize,status,performance:perf(expectancy,pf)});function review(extra={}){return{status:'HEALTHY',asOf:'2026-08-09T12:00:00.000Z',sample:{status:'DEVELOPING',completedTrades:30},recentTrend:'STABLE',coverage:{percentage:90},strategies:[group('momentum',20)],qualityBands:[group('WATCH',10,2),group('STRONG',10,8)],qualityScoreRanges:[group('55-69'),group('80-89')],trendRegimes:[group('BULL'),group('RANGE',10,3)],volatilityRegimes:[group('HIGH_VOLATILITY',10,-2,.8),group('NORMAL_VOLATILITY')],riskRegimes:[group('RISK_ON')],symbols:[group('AAPL')],assetTypes:[group('equity')],months:[group('2026-08')],...extra}}
describe('paper learning evidence',()=>{
 it('handles no trades and insufficient sample',()=>{const e=buildPaperLearningEvidence(review({status:'INSUFFICIENT_SAMPLE',sample:{status:'INSUFFICIENT_SAMPLE',completedTrades:0},strategies:[],qualityBands:[]}));expect(e.status).toBe('INSUFFICIENT_EVIDENCE');expect(e.reviewActions).toContain('INSUFFICIENT_EVIDENCE')})
 it('returns mature evidence only for healthy calibrated samples',()=>expect(buildPaperLearningEvidence(review()).status).toBe('MATURE'))
 it.each([[group('strong',50,10,1.5,'ESTABLISHED'),'STABLE'],[group('weak',10,0,.8),'CAUTION'],[group('bad',10,-10,.5),'DEGRADED'],[{value:'tiny',sampleSize:2,status:'INSUFFICIENT_SAMPLE'},'INSUFFICIENT_SAMPLE']])('classifies strategy evidence', (strategy,state)=>expect(buildPaperLearningEvidence(review({strategies:[strategy]})).strategyEvidence[0].evidenceState).toBe(state))
 it('preserves bull range volatility risk symbol and asset evidence',()=>{const e=buildPaperLearningEvidence(review());expect(e.regimeEvidence.trend.map(x=>x.regime)).toEqual(['BULL','RANGE']);expect(e.regimeEvidence.volatility.some(x=>x.regime==='HIGH_VOLATILITY')).toBe(true);expect(e.regimeEvidence.risk[0].regime).toBe('RISK_ON');expect(e.symbolEvidence[0].value).toBe('AAPL');expect(e.assetTypeEvidence[0].value).toBe('equity')})
 it('preserves quality bands and score-range evidence from PA.3',()=>{const e=buildPaperLearningEvidence(review());expect(e.qualityCalibration.groups.map(x=>x.value)).toEqual(['WATCH','STRONG']);expect(e.periodEvidence[0].value).toBe('2026-08')})
 it.each([[[group('WATCH',5,1),group('STRONG',5,2)],'CONSISTENT'],[[group('WATCH',5,3),group('STRONG',5,1)],'INVERTED'],[[group('WATCH',5,1),group('QUALIFIED',5,3),group('STRONG',5,2)],'MIXED'],[[group('WATCH',5,1),group('STRONG',20,2)],'UNSTABLE'],[[group('STRONG',4,2)],'INSUFFICIENT_DATA']])('classifies quality calibration', (qualityBands,status)=>expect(buildPaperLearningEvidence(review({qualityBands})).qualityCalibration.status).toBe(status))
 it.each(['IMPROVING','STABLE','DETERIORATING'])('preserves recent trend %s',(recentTrend)=>expect(buildPaperLearningEvidence(review({recentTrend})).recentTrend).toBe(recentTrend))
 it('discloses unequal calibration samples',()=>{const e=buildPaperLearningEvidence(review({qualityBands:[group('WATCH',5,1),group('STRONG',20,2)]}));expect(e.qualityCalibration.sampleRatio).toBe(4);expect(e.qualityCalibration.reason).toMatch(/differ materially/)})
 it('produces deterministic observations, actions, and stable ordering',()=>{const input=review({strategies:[group('zeta'),group('alpha',10,-1,.5)],recentTrend:'DETERIORATING'});const a=buildPaperLearningEvidence(input),b=buildPaperLearningEvidence(input);expect(a).toEqual(b);expect(a.strategyEvidence.map(x=>x.strategyId)).toEqual(['alpha','zeta']);expect(a.observations.join(' ')).toMatch(/deteriorated/);expect(a.reviewActions).toContain('REVIEW_STRATEGY_EVIDENCE')})
 it('cannot mutate strategies weights regimes risk providers or AI',()=>{const spy=vi.fn();const e=buildPaperLearningEvidence(review(),{strategyMutation:spy,weightMutation:spy,regimeMutation:spy,riskMutation:spy,provider:spy,ai:spy});expect(spy).not.toHaveBeenCalled();expect(e.boundaries).toMatchObject({automaticOptimization:false,automaticStrategyChanges:false,scoringWeightsChanged:false,regimeThresholdsChanged:false,riskLimitsChanged:false})})
})
describe('paper learning endpoint',()=>{it('requires authentication',async()=>{const h=createPaperLearningHandler();expect((await h({httpMethod:'GET',headers:{},queryStringParameters:{organizationId:'o'}})).statusCode).toBe(401)});it('uses tenant-scoped sources',async()=>{const listPaperSimulations=vi.fn(async()=>[]),listScoped=vi.fn(async()=>[]);const h=createPaperLearningHandler({opportunityRepository:{listPaperSimulations},repositoryFactory:()=>({getStore:()=>({listScoped}),end:vi.fn()}),authProvider:{authenticate:async()=>({ok:true,user:{id:'u',status:'active'},session:{id:'s',userId:'u',status:'active',expiresAt:'2099-01-01T00:00:00Z'}})},authorizationService:{assert:()=>({allowed:true})},organizationMembershipRepository:{getMembership:async()=>({organizationId:'o',userId:'u',role:'viewer',status:'active'})}});const r=await h({httpMethod:'GET',headers:{authorization:'Bearer x'},queryStringParameters:{organizationId:'o',accountId:'paper-portfolio'}});expect(r.statusCode).toBe(200);expect(listPaperSimulations).toHaveBeenCalledWith(expect.objectContaining({tenantContext:expect.objectContaining({organizationId:'o'}),userId:'u'}));expect(listScoped).toHaveBeenCalled()})})
