import { describe,expect,it,vi } from 'vitest'
import { simulateApprovedPaperEvaluations } from '../lib/opportunities/paperSimulation/index.js'
import { createPaperOrderSimulationHandler, edge2CohortFor } from '../netlify/functions/paper-order-simulation.js'
import { auth2Body, auth2Headers } from './helpers/auth2Fixtures.js'
const now='2026-08-09T12:00:00.000Z';const portfolio={id:'paper',cash:100000,equity:100000,buyingPower:100000,positions:[]};const portfolioRisk={account:{accountValue:100000,cash:100000,buyingPower:100000},summary:{openRisk:0,openRiskPct:0,drawdownPct:0}}
const executionQuote={symbol:'AAPL',price:100,bid:99.98,ask:100.02,bidSize:10000,askSize:10000,liquidityScore:80,updatedAt:now,receivedAt:now,provider:'test-top-of-book',provenance:{provider:'test-top-of-book',dataStatus:'LIVE',fallbackUsed:false,receivedAt:now}}
function evaluation(overrides={}){return {evaluationId:'eval-1',candidateId:'candidate-1',symbol:'AAPL',strategyId:'momentum',status:'APPROVED_FOR_PAPER_REVIEW',freshness:'FRESH',evaluatedAt:now,evidenceFingerprint:'evidence-1',engineVersions:{tradeQuality:'trade-quality-v1'},orderContext:{assetType:'equity',side:'buy',orderType:'market',price:100,stopPrice:98},...overrides}}
function run(overrides={},options={}){return simulateApprovedPaperEvaluations({evaluations:[evaluation()],portfolio,portfolioRisk,enabled:true,executionQuotes:[executionQuote],...overrides},{now,confirmedAt:now,confirmationSource:'authenticated_manual_request',...options})}
describe('guarded paper order simulation',()=>{
 it('fails closed',()=>expect(simulateApprovedPaperEvaluations({evaluations:[evaluation()],portfolio,portfolioRisk},{now}).results).toEqual([]))
 it.each(['WATCH','REJECTED','STALE','INSUFFICIENT_DATA','ERROR'])('%s is ineligible',(status)=>expect(run({evaluations:[evaluation({status})]}).results).toEqual([]))
 it('requires explicit order context',()=>expect(run({evaluations:[evaluation({orderContext:{}})]}).results[0].status).toBe('INSUFFICIENT_ORDER_CONTEXT'))
 it('admits paper simulation without claiming live calibration',()=>{const x=run().results[0];expect(x.orderPlan.quantity).toBeGreaterThan(0);expect(x.guardrail.approved).toBe(true);expect(x.status).toBe('SIMULATED_FILLED');expect(x.executionFill.quantity).toBe(x.orderPlan.quantity);expect(x).toMatchObject({executionCalibrationStatus:'PAPER_ONLY_NOT_LIVE_CALIBRATED',paperTradingOnly:true,liveOrders:false,brokerExecution:false,automaticExecution:false,canonicalLedgerOutcome:{status:'PENDING_COMMIT'},executionRealism:{paperSimulationAdmissibility:{status:'ADMISSIBLE'},liveExecutionCalibration:{status:'NOT_CALIBRATED',liveMoneyReady:false}}})})
 it('rejects insufficient buying power',()=>expect(['INSUFFICIENT_ORDER_CONTEXT','SIMULATION_REJECTED']).toContain(run({portfolioRisk:{account:{accountValue:100000,cash:0,buyingPower:0},summary:{openRisk:0,openRiskPct:0}}}).results[0].status))
 it('enforces cycle and daily limits',()=>{const evaluations=Array.from({length:5},(_,i)=>evaluation({evaluationId:`e${i}`,candidateId:`c${i}`}));expect(run({evaluations}).results).toHaveLength(3);expect(run({evaluations,dailyCount:10}).results).toHaveLength(0)})
 it('suppresses duplicates but changed evidence proceeds',()=>{const first=run().results[0];expect(run({existingSimulations:[first]}).results[0].status).toBe('DUPLICATE_SUPPRESSED');expect(run({evaluations:[evaluation({evidenceFingerprint:'evidence-2'})],existingSimulations:[first]}).results[0].status).not.toBe('DUPLICATE_SUPPRESSED')})
 it('marks expired evidence stale',()=>expect(simulateApprovedPaperEvaluations({evaluations:[evaluation({evaluatedAt:'2026-08-01T00:00:00.000Z'})],portfolio,portfolioRisk,enabled:true},{now}).results[0].status).toBe('STALE'))
 it('stores no sensitive payload and calls no external subsystem',()=>{const spy=vi.fn();const x=run({provider:spy,broker:spy,ai:spy}).results[0];expect(spy).not.toHaveBeenCalled();expect(JSON.stringify(x)).not.toMatch(/rawCandles|apiKey|prompt|providerCredential/i)})
 it('never substitutes last price when executable bid/ask evidence is absent',()=>{const lastOnly={symbol:'AAPL',price:100,updatedAt:now,receivedAt:now,provider:'test',dataStatus:'LIVE',fallbackUsed:false};const x=run({executionQuotes:[lastOnly]}).results[0];expect(x.status).toBe('INSUFFICIENT_EXECUTION_EVIDENCE');expect(x.executionRealism.missingEvidence).toEqual(expect.arrayContaining(['authoritative_bid','authoritative_ask','authoritative_ask_size']));expect(x.executionFill).toBeNull()})
 it('fails closed instead of filling beyond displayed executable size',()=>{const thin={...executionQuote,askSize:10};const x=run({executionQuotes:[thin]}).results[0];expect(x.orderPlan.quantity).toBeGreaterThan(10);expect(x.status).toBe('INSUFFICIENT_EXECUTION_EVIDENCE');expect(x.executionRealism.missingEvidence).toContain('displayed_size_for_full_quantity');expect(x.executionFill).toBeNull()})
 it('records latency, spread, fill and exactly-once paper costs while live calibration remains blocked',()=>{const decisionAt='2026-08-09T11:59:30.000Z';const x=run({evaluations:[evaluation({evaluatedAt:decisionAt})]}).results[0];expect(x.executionRealism).toMatchObject({version:'paper-execution-realism-v2',calibrationStatus:'PAPER_ONLY_NOT_LIVE_CALIBRATED',evidenceStatus:'SUFFICIENT_FOR_PAPER_SIMULATION',paperSimulationAdmissibility:{status:'ADMISSIBLE'},liveExecutionCalibration:{status:'NOT_CALIBRATED',liveMoneyReady:false},chronology:{decisionAt,confirmedAt:now,submittedAt:now,decisionToConfirmationMs:30000,confirmationToSubmissionMs:0},quoteEvidence:{bid:99.98,ask:100.02,spread:0.04,spreadBps:4},quantityEvidence:{fullQuantityDisplayed:true},deterministicAssumptions:{spreadTreatment:'preserve_quote_and_use_executable_side_once',costsTreatment:'executable_side_then_slippage_once_and_fees_once',fillModel:'paper_top_of_book_displayed_size_v1'},fillEvidence:{status:'PAPER_FILLED',referencePrice:100.02,slippageBps:5,costApplications:{spread:1,slippage:1,fees:1}}});expect(x.executionFill).toMatchObject({referencePrice:100.02,slippageBps:5});expect(x.executionFill.fillPrice).toBeGreaterThan(100.02);expect(x.executionFill.fees).toBeGreaterThan(0)})
})
describe('endpoint security',()=>{it('requires authenticated CSRF request',async()=>{const handler=createPaperOrderSimulationHandler({env:{PAPER_AUTOMATION_ENABLED:'true'}});expect((await handler({httpMethod:'POST',headers:auth2Headers({csrf:false}),body:JSON.stringify(auth2Body())})).statusCode).toBe(403)})})

describe('EDGE.2 durable cohort linkage',()=>{
 it('requires an exact persisted evaluation snapshot and approved exit definition',async()=>{
  const evaluated=evaluation({strategyId:'index-pullback-v1',evidenceFingerprint:'evidence-a'})
  const manifest={observationId:'edge-a',manifestFingerprint:'manifest-a',exitPolicy:{version:'index-pullback-exit-v1.0.0',policyFingerprint:'policy-a'}}
  const snapshot={experimentId:'EDGE.2',observationId:'edge-a',manifestFingerprint:'manifest-a',evaluationId:'eval-1',evaluationEvidenceFingerprint:'evidence-a',symbol:'AAPL',strategyId:'index-pullback-v1'}
  const repository={getForwardObservationManifest:vi.fn(async()=>({status:'collecting',manifest})),listForwardEvidenceSnapshots:vi.fn(async()=>[snapshot])}
  const simulation={exitPolicy:{version:manifest.exitPolicy.version,definitionFingerprint:'policy-a'}}
  await expect(edge2CohortFor(repository,{},evaluated,simulation)).resolves.toEqual({experimentId:'EDGE.2',observationId:'edge-a',manifestFingerprint:'manifest-a'})
  await expect(edge2CohortFor(repository,{},evaluated,{exitPolicy:{...simulation.exitPolicy,definitionFingerprint:'wrong'}})).resolves.toBeNull()
  await expect(edge2CohortFor({...repository,listForwardEvidenceSnapshots:async()=>[{...snapshot,evaluationId:'other'}]}, {}, evaluated, simulation)).resolves.toBeNull()
 })
})
