import{describe,expect,it,vi}from'vitest';import{simulatePaperPositionExit}from'../lib/opportunities/paperExit/index.js';import{reviewPaperPerformance}from'../lib/analytics/paperPerformanceReview.js';import{createPaperPositionExitHandler}from'../netlify/functions/paper-position-exit.js'
import{listPaperPositionAggregates,savePaperExitAggregate}from'../lib/opportunities/paperExit/paperPositionStore.js'
import{auth2Body,auth2Headers}from'./helpers/auth2Fixtures.js'
const now='2026-08-09T12:00:00.000Z',quote={price:110,updatedAt:'2026-08-09T11:59:00.000Z',liquidityScore:80},account={accountId:'paper',cash:9000,equity:10000,realizedPnl:25};function position(extra={}){return{positionId:'pos-1',symbol:'AAPL',assetType:'equity',side:'long',quantity:100,averagePrice:100,currentPrice:108,originatingCandidateId:'c1',originatingEvaluationId:'e1',strategyId:'momentum',tradeQuality:{score:85,band:'STRONG'},regime:{trendRegime:'BULL'},...extra}}function run(extra={},opts={}){return simulatePaperPositionExit({position:position(),account,quantity:100,quote,...extra},{now,...opts})}
describe('guarded paper exit lifecycle',()=>{
 it('fully closes a long position with realized profit and cash impact',()=>{const r=run();expect(r.status).toBe('POSITION_CLOSED');expect(r.exitPlan.remainingQuantity).toBe(0);expect(r.exitPlan.realizedPnlDelta).toBeGreaterThan(0);expect(r.accountSnapshot.cash).toBeGreaterThan(account.cash);expect(r.positionSnapshot).toBeNull()})
 it('partially reduces a long position and preserves cost basis',()=>{const r=run({quantity:40});expect(r.status).toBe('POSITION_REDUCED');expect(r.exitPlan.remainingQuantity).toBe(60);expect(r.positionSnapshot.averagePrice).toBe(100);expect(r.exitPlan.realizedPnlDelta).toBeGreaterThan(0)})
 it('closes and reduces supported short positions',()=>{const p=position({symbol:'MSFT',side:'short',quantity:10,averagePrice:120});const full=run({position:p,quantity:10,quote:{...quote,price:100}}),partial=run({position:p,quantity:4,quote:{...quote,price:100}});expect(full.status).toBe('POSITION_CLOSED');expect(full.exitPlan.realizedPnlDelta).toBeGreaterThan(0);expect(partial.status).toBe('POSITION_REDUCED');expect(partial.exitPlan.remainingQuantity).toBe(6)})
 it.each([[101,'exceeds'],[0,'greater than zero'],[-1,'greater than zero']])('rejects invalid quantity %s',(quantity,message)=>{const r=run({quantity});expect(r.status).toBe('REJECTED');expect(r.blockers[0]).toContain(message)})
 it.each([[{averagePrice:null},'INSUFFICIENT_EXIT_CONTEXT'],[{side:null},'INSUFFICIENT_EXIT_CONTEXT']])('rejects missing context', (override,status)=>expect(run({position:position(override)}).status).toBe(status))
 it('rejects missing and stale reference prices',()=>{expect(run({quote:{updatedAt:quote.updatedAt}}).status).toBe('INSUFFICIENT_EXIT_CONTEXT');expect(run({quote:{price:110,updatedAt:'2026-08-09T10:00:00.000Z'}}).status).toBe('STALE')})
 it('fails when paper mode is disabled',()=>expect(run({paperModeEnabled:false}).status).toBe('REJECTED'))
 it('suppresses duplicates without repeating accounting',()=>{const first=run();const duplicate=run({existingExits:[first]});expect(duplicate.status).toBe('DUPLICATE_SUPPRESSED');expect(duplicate.accountSnapshot).toBeUndefined()})
 it('never reverses a position',()=>{const r=run({quantity:150});expect(r.status).toBe('REJECTED');expect(r.positionSnapshot).toBeUndefined()})
 it('calculates deterministic realized loss and cumulative P&L',()=>{const r=run({quote:{...quote,price:90}});expect(r.exitPlan.realizedPnlDelta).toBeLessThan(0);expect(r.accountSnapshot.realizedPnl).toBeCloseTo(25+r.exitPlan.realizedPnlDelta,2)})
 it('creates normalized journal and origin linkage',()=>{const r=run();expect(r).toMatchObject({candidateId:'c1',evaluationId:'e1',journal:{journalStatus:'recorded'},paperTradingOnly:true,automaticExecution:false,liveOrders:false,brokerExecution:false})})
 it('becomes PA.3 eligible only after realized exit',()=>{const open=reviewPaperPerformance([{id:'open',status:'SIMULATED_FILLED',accountingStatus:'position_created',realizedPnl:0,paperTradingOnly:true}],{asOf:now});const exit=run();const closed=reviewPaperPerformance([{id:exit.fingerprint,status:'SIMULATED_FILLED',accountingStatus:'position_closed',realizedPnl:exit.exitPlan.realizedPnlDelta,paperTradingOnly:true}],{asOf:now});expect(open.sample.completedTrades).toBe(0);expect(closed.sample.completedTrades).toBe(1)})
 it('has no broker AI strategy scanner or unattended dependency',()=>{const spy=vi.fn();run({broker:spy,ai:spy,strategy:spy,scanner:spy,scheduler:spy});expect(spy).not.toHaveBeenCalled()})
})
describe('paper exit endpoint security',()=>{it('requires authentication',async()=>{const handler=createPaperPositionExitHandler();const r=await handler({httpMethod:'GET',headers:{},queryStringParameters:{organizationId:'org-a'}});expect(r.statusCode).toBe(401)});it('requires CSRF for mutation',async()=>{const handler=createPaperPositionExitHandler();const r=await handler({httpMethod:'POST',headers:auth2Headers({csrf:false}),body:JSON.stringify(auth2Body())});expect(r.statusCode).toBe(403)})})
describe('paper position persistence boundary',()=>{it('filters aggregates by tenant and user',async()=>{const rows=[{payload:{kind:'paper-position-lifecycle-v1',ownerUserId:'u1',tenantScope:{organizationId:'o1'},position:position()}},{payload:{kind:'paper-position-lifecycle-v1',ownerUserId:'u2',tenantScope:{organizationId:'o1'},position:position({positionId:'other'})}}];const repository={getStore:()=>({listScoped:vi.fn(async()=>rows)})};const result=await listPaperPositionAggregates(repository,{organizationId:'o1',userId:'u1'});expect(result).toHaveLength(1);expect(result[0].ownerUserId).toBe('u1')});it('writes position accounting exit and journal as one aggregate upsert',async()=>{const upsertScoped=vi.fn(async()=>({ok:true}));const repository={getStore:()=>({upsertScoped})};const aggregate={kind:'paper-position-lifecycle-v1',ownerUserId:'u1',tenantScope:{organizationId:'o1',userId:'u1'},position:position(),account,exits:[]};const exit=run();await savePaperExitAggregate(repository,aggregate,exit,{organizationId:'o1',userId:'u1'});expect(upsertScoped).toHaveBeenCalledTimes(1);expect(upsertScoped.mock.calls[0][1]).toMatchObject({position:null,account:expect.objectContaining({realizedPnl:expect.any(Number)}),exits:[expect.objectContaining({journal:expect.objectContaining({journalStatus:'recorded'})})]})})})
