export const ADAPTIVE_STRATEGY_ENGINE_VERSION = 'adaptive-strategy-v1'

export const STRATEGY_SUITABILITY_DECISIONS = Object.freeze({
  ENABLED: 'ENABLED',
  CONDITIONAL: 'CONDITIONAL',
  DISABLED: 'DISABLED',
  UNKNOWN: 'UNKNOWN',
})

export const STRATEGY_SUITABILITY_STATUSES = Object.freeze({
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  INVALID_INPUT: 'INVALID_INPUT',
})
