import { EmptyWorkspaceState, MetricCard, WorkspacePanel } from '../../components/workspace/WorkspacePage.jsx'
import { usePaperPerformanceReview } from '../../hooks/usePaperPerformanceReview.js'
import { usePaperLearning } from '../../hooks/usePaperLearning.js'
import { buildDecisionQualityMonitor } from '../../../lib/analytics/decisionQualityMonitor.js'

const display=value=>String(value??'UNKNOWN').replaceAll('_',' ')
export function PaperLearningPanel({state}={}){const live=usePaperLearning(),resolved=state??live,e=resolved.evidence;return <WorkspacePanel id="paper-learning" title="Paper Learning / Evidence" subtitle="What is working, weak, inconclusive, or changing">
 {resolved.isLoading?<p role="status">Loading realized paper evidence…</p>:null}{resolved.error?<p role="alert">Paper learning evidence is unavailable.</p>:null}{!resolved.isLoading&&!resolved.error&&!e?<EmptyWorkspaceState>No realized paper learning evidence is available.</EmptyWorkspaceState>:null}
 {e?<><p><strong>{display(e.status)}</strong> · {e.sample.completedTrades??0} realized trades · Performance: {display(e.performanceStatus)} · Recent: {display(e.recentTrend)}</p><div className="metric-grid"><MetricCard label="Evidence Maturity" value={display(e.sample.status)}/><MetricCard label="Quality Calibration" value={display(e.qualityCalibration.status)}/><MetricCard label="Strategies Reviewed" value={e.strategyEvidence.length}/><MetricCard label="Coverage" value={`${e.coverage.percentage??0}%`}/></div>{e.sample.status==='INSUFFICIENT_SAMPLE'?<p role="status">Sample too small for strong conclusions; continue paper observation.</p>:null}<details open><summary>Strategy evidence</summary>{e.strategyEvidence.length?e.strategyEvidence.map(x=><p key={x.strategyId}><strong>{x.strategyId}: {display(x.evidenceState)}</strong> · {x.sampleSize} trades · expectancy {x.performance?.expectancyPerTrade??'unavailable'}</p>):<p>No strategy group has realized evidence.</p>}</details><details><summary>Quality and regime evidence</summary><p>Calibration: {display(e.qualityCalibration.status)} — {e.qualityCalibration.reason}</p><p>Trend groups: {e.regimeEvidence.trend.map(x=>`${display(x.regime)} (${x.sampleSize})`).join(', ')||'insufficient'}</p><p>Volatility groups: {e.regimeEvidence.volatility.map(x=>`${display(x.regime)} (${x.sampleSize})`).join(', ')||'insufficient'}</p><p>Risk groups: {e.regimeEvidence.risk.map(x=>`${display(x.regime)} (${x.sampleSize})`).join(', ')||'insufficient'}</p></details><h3>Operator observations</h3><ul>{e.observations.map(x=><li key={x}>{x}</li>)}</ul><p>Review actions: {e.reviewActions.map(display).join(' · ')||'Continue observation'}</p><p>PAPER ONLY · Descriptive correlation, not causation. No strategy, scoring, regime, risk, or execution setting changes automatically.</p></>:null}
 </WorkspacePanel>}

export function PaperPerformanceReviewPanel({state}={}){const live=usePaperPerformanceReview();const resolved=state??live,review=resolved.review,observation=review?.forwardObservation;return <WorkspacePanel id="paper-performance-review" title="Paper Performance Review" subtitle="Deterministic strategy feedback · advisory only">
  {resolved.isLoading?<p role="status">Loading completed paper performance…</p>:null}{resolved.error?<p role="alert">Paper performance review is unavailable.</p>:null}
  {!resolved.isLoading&&!resolved.error&&!review?<EmptyWorkspaceState>No paper performance review is available.</EmptyWorkspaceState>:null}
  {review?<><p><strong>{String(review.status).replaceAll('_',' ')}</strong> · {review.sample.completedTrades} completed trades · Sample: {String(review.sample.status).replaceAll('_',' ')}</p><div className="metric-grid"><MetricCard label="Win Rate" value={`${review.performance.winRate}%`}/><MetricCard label="Expectancy" value={`$${review.performance.expectancyPerTrade}`}/><MetricCard label="Profit Factor" value={review.performance.profitFactor}/><MetricCard label="Net Realized P&L" value={`$${review.performance.netRealizedPnl}`}/><MetricCard label="Max Drawdown" value={`${review.performance.maximumDrawdownPct}%`}/><MetricCard label="Recent Trend" value={review.recentTrend}/></div>{review.sample.status==='INSUFFICIENT_SAMPLE'?<p role="status">Small sample: results cannot establish profitability or reliability.</p>:null}{observation?<section aria-labelledby="forward-evidence-heading"><h3 id="forward-evidence-heading">Forward Evidence Observation</h3><p><strong>{display(observation.status)}</strong>{observation.observationId?` · ${observation.observationId}`:''}</p><div className="metric-grid"><MetricCard label="Trading Sessions" value={`${observation.sessionsElapsed}/${observation.minimumSessions}`}/><MetricCard label="Completed Outcomes" value={`${observation.completedOutcomes}/${observation.minimumOutcomes}`}/><MetricCard label="Session Progress" value={`${observation.sessionProgressPct??0}%`}/><MetricCard label="Outcome Progress" value={`${observation.outcomeProgressPct??0}%`}/></div>{observation.reviewClassification?<p>Review classification: <strong>{display(observation.reviewClassification)}</strong></p>:<p role="status">No profitability classification is permitted until both minimums are met.</p>}{observation.blockers?.length?<p>Blockers: {observation.blockers.map(display).join(' · ')}</p>:null}<p><strong>PAPER ONLY</strong> · NO OPTIMIZATION DURING OBSERVATION · Frozen experiment {observation.manifestFingerprint?.slice(0,12)??'not started'}.</p></section>:null}<h3>Deterministic feedback</h3><ul>{review.feedback.map(x=><li key={x}>{x}</li>)}</ul><details><summary>Strategy, quality, and regime evidence</summary><p>Strategies: {review.strategies.map(x=>`${x.value} (${x.sampleSize})`).join(', ')||'Insufficient data'}</p><p>Quality bands: {review.qualityBands.map(x=>`${x.value} (${x.sampleSize})`).join(', ')||'Insufficient data'}</p><p>Trend regimes: {review.trendRegimes.map(x=>`${x.value} (${x.sampleSize})`).join(', ')||'Insufficient data'}</p></details><p>PAPER ONLY · Advisory feedback only. No strategy, risk, scoring, or execution settings are changed.</p></>:null}
 </WorkspacePanel>}

export function DecisionQualityPanel({state}={}){const live=usePaperPerformanceReview(),resolved=state??live,review=resolved.review,monitor=review?buildDecisionQualityMonitor({performanceReview:review,generatedAt:review.asOf}):null;return <WorkspacePanel id="decision-quality" title="Decision Quality" subtitle="Past paper evidence · descriptive only">
 {resolved.isLoading?<p role="status">Loading decision quality evidence…</p>:null}{resolved.error?<p role="alert">Decision quality evidence is unavailable.</p>:null}{!resolved.isLoading&&!resolved.error&&!monitor?<EmptyWorkspaceState>No completed decision evidence is available.</EmptyWorkspaceState>:null}
 {monitor?<><p><strong>{display(monitor.status)}</strong> · PAST PAPER EVIDENCE · NOT A GUARANTEE OF FUTURE PERFORMANCE</p><div className="metric-grid"><MetricCard label="Completed Outcomes" value={monitor.overall.completedOutcomes}/><MetricCard label="Expectancy" value={`$${monitor.overall.expectancy}`}/><MetricCard label="Profit Factor" value={monitor.overall.profitFactor}/><MetricCard label="Average R" value={monitor.rNormalized.metrics?.averageR??'Unavailable'}/><MetricCard label="Drawdown" value={`${monitor.overall.maxDrawdown}%`}/><MetricCard label="Recent Trend" value={display(monitor.recentTrend)}/></div><details><summary>Strategy, regime, and TQ evidence</summary><p>Strategies: {monitor.groupings.byStrategyId.map(x=>`${x.value} (${x.sampleSize})`).join(', ')||'unavailable'}</p><p>Trend regimes: {monitor.groupings.byRegime.trend.map(x=>`${x.value} (${x.sampleSize})`).join(', ')||'unavailable'}</p><p>TQ calibration: {display(monitor.tqCalibration.status)}</p></details><p>R-normalized evidence: {display(monitor.rNormalized.status)}{monitor.rNormalized.reason?` · ${monitor.rNormalized.reason}`:''}</p><p>Fingerprint compatibility: {display(monitor.compatibility.status)}. No optimization, strategy change, or execution action is available.</p></>:null}
 </WorkspacePanel>}

export function ReportSections() {
  return (
    <>
      <WorkspacePanel id="paper-reports" title="Paper Reports" subtitle="Reporting outputs">
        <div className="metric-grid">
          <MetricCard label="Audit" value="available" />
          <MetricCard label="Exports" value="CSV / JSON" />
          <MetricCard label="History" value="paper mode" />
          <MetricCard label="Operator Reports" value="review" />
        </div>
      </WorkspacePanel>
      <WorkspacePanel id="exports" title="Exports" subtitle="CSV and JSON">
        <EmptyWorkspaceState>Exports remain report artifacts only and do not change trading state.</EmptyWorkspaceState>
      </WorkspacePanel>
      <PaperPerformanceReviewPanel />
      <DecisionQualityPanel />
      <PaperLearningPanel />
    </>
  )
}
