export const MARKET_REGIME_ENGINE_VERSION = 'market-regime-v1'

export const TREND_REGIMES = Object.freeze({
  STRONG_BULL: 'STRONG_BULL', BULL: 'BULL', RANGE: 'RANGE', BEAR: 'BEAR', STRONG_BEAR: 'STRONG_BEAR', UNKNOWN: 'UNKNOWN',
})

export const VOLATILITY_REGIMES = Object.freeze({
  HIGH: 'HIGH_VOLATILITY', NORMAL: 'NORMAL_VOLATILITY', LOW: 'LOW_VOLATILITY', UNKNOWN: 'UNKNOWN',
})

export const RISK_REGIMES = Object.freeze({
  ON: 'RISK_ON', NEUTRAL: 'NEUTRAL', OFF: 'RISK_OFF', UNKNOWN: 'UNKNOWN',
})

export const REGIME_STATUSES = Object.freeze({
  COMPLETE: 'COMPLETE', PARTIAL: 'PARTIAL', INSUFFICIENT: 'INSUFFICIENT_DATA', INVALID: 'INVALID_INPUT',
})
