import { describe, expect, it } from 'vitest'
import { renderToStaticMarkup } from 'react-dom/server'
import App from './App'

describe('App', () => {
  it('renders the portfolio risk dashboard', () => {
    const markup = renderToStaticMarkup(<App />)

    expect(markup).toContain('Portfolio Risk Intelligence')
    expect(markup).toContain('Paper Trading only')
    expect(markup).toContain('portfolio.risk.evaluated')
    expect(markup).toContain('Trade Guardrails')
    expect(markup).toContain('trade.guardrail.evaluated')
    expect(markup).toContain('approved')
    expect(markup).toContain('rejected')
    expect(markup).toContain('Execution Simulation')
    expect(markup).toContain('trade.execution.simulated')
    expect(markup).toContain('Fill Price')
    expect(markup).toContain('Fees')
    expect(markup).toContain('Paper Accounting')
    expect(markup).toContain('portfolio.accounting.updated')
    expect(markup).toContain('Realized P&amp;L')
    expect(markup).toContain('Paper Trade Journal')
    expect(markup).toContain('trade.journal.recorded')
    expect(markup).toContain('Decision Gate')
    expect(markup).toContain('Paper Performance')
    expect(markup).toContain('portfolio.performance.evaluated')
    expect(markup).toContain('Profit Factor')
    expect(markup).toContain('Portfolio Analytics')
    expect(markup).toContain('portfolio.analytics.updated')
    expect(markup).toContain('Diversification')
    expect(markup).toContain('Drift')
    expect(markup).toContain('Rebalancing Recommendations')
    expect(markup).toContain('portfolio.rebalance.recommended')
    expect(markup).toContain('Recommendations only')
    expect(markup).toContain('Strategy Attribution')
    expect(markup).toContain('strategy.attribution.evaluated')
    expect(markup).toContain('Index Pullback')
  })
})
