import { describe, expect, it } from 'vitest'
import { renderToStaticMarkup } from 'react-dom/server'
import App from './App'

describe('App', () => {
  it('renders the portfolio risk dashboard', () => {
    const markup = renderToStaticMarkup(<App />)

    expect(markup).toContain('Portfolio Risk Intelligence')
    expect(markup).toContain('Paper Trading only')
    expect(markup).toContain('Institutional trading workspace')
    expect(markup).toContain('Paper Trading OS')
    expect(markup).toContain('portfolio.risk.evaluated')
    expect(markup).toContain('Scanner / Signal Panel')
    expect(markup).toContain('Momentum Pullback')
    expect(markup).toContain('Risk Panel')
    expect(markup).toContain('Trade Guardrails')
    expect(markup).toContain('trade.guardrail.evaluated')
    expect(markup).toContain('approved')
    expect(markup).toContain('rejected')
    expect(markup).toContain('Execution Simulation')
    expect(markup).toContain('trade.execution.simulated')
    expect(markup).toContain('Fill Price')
    expect(markup).toContain('Fees')
    expect(markup).toContain('Paper Accounting')
    expect(markup).toContain('portfolio.accounting.updated')
    expect(markup).toContain('Realized P&amp;L')
    expect(markup).toContain('Paper Trade Journal')
    expect(markup).toContain('trade.journal.recorded')
    expect(markup).toContain('Decision Gate')
    expect(markup).toContain('Paper Performance')
    expect(markup).toContain('portfolio.performance.evaluated')
    expect(markup).toContain('Profit Factor')
    expect(markup).toContain('Risk-Adjusted Performance')
    expect(markup).toContain('portfolio.riskAdjustedPerformance.evaluated')
    expect(markup).toContain('Sharpe-style Score')
    expect(markup).toContain('Recovery Factor')
    expect(markup).toContain('Drawdown Protection')
    expect(markup).toContain('portfolio.drawdownProtection.evaluated')
    expect(markup).toContain('Protection Status')
    expect(markup).toContain('Current Drawdown')
    expect(markup).toContain('Position Sizing')
    expect(markup).toContain('trade.positionSize.recommended')
    expect(markup).toContain('Buying Power Cap')
    expect(markup).toContain('Max Position Cap')
    expect(markup).toContain('Capital Allocation')
    expect(markup).toContain('portfolio.capitalAllocation.recommended')
    expect(markup).toContain('Available Capital')
    expect(markup).toContain('Strategy Allocation')
    expect(markup).toContain('AI Decision Orchestrator')
    expect(markup).toContain('ai.decision.orchestrated')
    expect(markup).toContain('Signal Quality')
    expect(markup).toContain('Risk Approval')
    expect(markup).toContain('Multi-Strategy Manager')
    expect(markup).toContain('strategy.portfolioManager.evaluated')
    expect(markup).toContain('Strategy Approval Status')
    expect(markup).toContain('Duplicate Symbols')
    expect(markup).toContain('Event Timeline')
    expect(markup).toContain('Event-driven paper trading lifecycle sequence')
    expect(markup).toContain('Market Data Health')
    expect(markup).toContain('marketData.adapter.checked')
    expect(markup).toContain('Mock adapter default')
    expect(markup).toContain('Stale Data')
    expect(markup).toContain('Portfolio Analytics')
    expect(markup).toContain('portfolio.analytics.updated')
    expect(markup).toContain('Diversification')
    expect(markup).toContain('Drift')
    expect(markup).toContain('Rebalancing Recommendations')
    expect(markup).toContain('portfolio.rebalance.recommended')
    expect(markup).toContain('Recommendations only')
    expect(markup).toContain('Strategy Attribution')
    expect(markup).toContain('strategy.attribution.evaluated')
    expect(markup).toContain('Index Pullback')
  })
})
