export const DEFAULT_TRADE_QUALITY_CONFIG = Object.freeze({
  weights: Object.freeze({
    regimeFit: 15,
    strategySuitability: 20,
    trend: 15,
    momentum: 10,
    relativeStrength: 10,
    volume: 10,
    volatility: 5,
    liquidity: 5,
    riskReward: 10,
  }),
  minimumCoverage: 55,
  minimumCoreDimensions: 2,
  caps: Object.freeze({ staleOrInvalidRegime: 54, partialRegime: 69, disabledStrategy: 54, failedLiquidity: 54, blockingPrerequisite: 54 }),
  thresholds: Object.freeze({
    relativeStrengthStrong: 5,
    relativeStrengthPositive: 0,
    relativeVolumeStrong: 1.5,
    relativeVolumeConfirmed: 1,
    spreadMaximumPct: 0.25,
    riskRewardStrong: 3,
    riskRewardAcceptable: 2,
    riskRewardMinimum: 1,
  }),
})
