export const TRADE_QUALITY_ENGINE_VERSION = 'trade-quality-v1'

export const TRADE_QUALITY_STATUSES = Object.freeze({
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  INVALID_INPUT: 'INVALID_INPUT',
})

export const TRADE_QUALITY_BANDS = Object.freeze({
  EXCEPTIONAL: 'EXCEPTIONAL',
  STRONG: 'STRONG',
  QUALIFIED: 'QUALIFIED',
  WATCH: 'WATCH',
  WEAK: 'WEAK',
  UNKNOWN: 'UNKNOWN',
})
