import { createHash } from 'node:crypto'
import { evaluateTradeGuardrail } from '../../../src/core/risk/tradeGuardrailEngine.js'
import { recommendPositionSize } from '../../../src/core/risk/positionSizingEngine.js'
import { simulateRealtimePaperExecution } from '../../trading/realTimeSimulatedExecutionCoordinator.js'
import { DEFAULT_PAPER_SIMULATION_CONFIG } from './paperSimulationConfig.js'

export const PAPER_SIMULATION_VERSION = 'guarded-paper-simulation-v1'
export const PAPER_SIMULATION_STATUSES = Object.freeze(['SIMULATED_FILLED','SIMULATION_REJECTED','DUPLICATE_SUPPRESSED','STALE','INSUFFICIENT_ORDER_CONTEXT','ERROR'])
const validSides = new Set(['buy','sell','short','cover'])
const finitePositive = (value) => Number.isFinite(Number(value)) && Number(value) > 0
function fingerprint(evaluation, plan) { return createHash('sha256').update(JSON.stringify([evaluation.evaluationId,evaluation.candidateId,evaluation.strategyId,evaluation.evidenceFingerprint,evaluation.engineVersions?.tradeQuality,evaluation.evaluatedAt,plan.side,plan.quantity,plan.referencePrice])).digest('hex') }
function insufficient(evaluation, blockers) { return { evaluationId:evaluation.evaluationId,candidateId:evaluation.candidateId,symbol:evaluation.symbol,strategyId:evaluation.strategyId,evaluationEvidenceFingerprint:evaluation.evidenceFingerprint??null,status:'INSUFFICIENT_ORDER_CONTEXT',blockers,paperTradingOnly:true,automaticExecution:false,engineVersion:PAPER_SIMULATION_VERSION } }

export function simulateApprovedPaperEvaluations({ evaluations=[], existingSimulations=[], portfolio={}, portfolioRisk, enabled=false, dailyCount=0 }={}, options={}) {
  const config=options.config ?? DEFAULT_PAPER_SIMULATION_CONFIG; const now=options.now ?? new Date().toISOString()
  if (!enabled) return { status:'BLOCKED', killSwitchEnabled:false, cycleLimit:config.cycleLimit, dailyLimit:config.dailyLimit, results:[], blocker:'Paper automation kill switch is disabled', paperTradingOnly:true, automaticExecution:false }
  const remaining=Math.max(0,config.dailyLimit-dailyCount); const selected=evaluations.filter(e=>e.status==='APPROVED_FOR_PAPER_REVIEW').slice(0,Math.min(config.cycleLimit,remaining)); const prior=new Set(existingSimulations.map(s=>s.fingerprint)); const results=[]
  for (const evaluation of selected) {
    const age=Date.parse(now)-Date.parse(evaluation.evaluatedAt); if (evaluation.freshness==='STALE'||!Number.isFinite(age)||age>config.maxEvidenceAgeMs) { results.push({...insufficient(evaluation,['Market evidence is stale']),status:'STALE'}); continue }
    const c=evaluation.orderContext ?? {}; const missing=[]; if(!validSides.has(c.side))missing.push('side'); if(!finitePositive(c.price))missing.push('referencePrice'); if(!finitePositive(c.stopPrice))missing.push('stopPrice');
    if(missing.length){results.push(insufficient(evaluation,missing.map(x=>`${x} is required`)));continue}
    const base={symbol:evaluation.symbol,assetType:c.assetType||'equity',side:c.side,orderType:c.orderType||'market',price:Number(c.price),stopPrice:Number(c.stopPrice),paperTrading:true}
    const sizing=recommendPositionSize(portfolio,base,{emitEvent:false,portfolioRisk,timestamp:now}); const quantity=finitePositive(c.quantity)?Number(c.quantity):sizing.suggestedQuantity
    if(sizing.status!=='recommended'||!finitePositive(quantity)){results.push(insufficient(evaluation,[sizing.reason||'Position sizing did not produce a valid quantity']));continue}
    const proposedTrade={...base,quantity}; const guardrail=evaluateTradeGuardrail(portfolio,proposedTrade,{emitEvent:false,currentRisk:portfolioRisk,timestamp:now});
    const plan={candidateId:evaluation.candidateId,evaluationId:evaluation.evaluationId,symbol:evaluation.symbol,assetType:base.assetType,strategyId:evaluation.strategyId,side:base.side,quantity,entryType:base.orderType,referencePrice:base.price,stopReference:base.stopPrice,targetReference:finitePositive(c.targetPrice)?Number(c.targetPrice):null,maximumRisk:guardrail.metrics?.dollarRisk??null,evidenceTimestamp:evaluation.evaluatedAt,guardrailResult:{approved:guardrail.approved,reason:guardrail.reason},paperTradingOnly:true}
    const key=fingerprint(evaluation,plan); if(prior.has(key)){results.push({...insufficient(evaluation,['Identical evaluation and evidence were already simulated']),status:'DUPLICATE_SUPPRESSED',fingerprint:key,orderPlan:plan});continue}
    if(!guardrail.approved){results.push({...insufficient(evaluation,[guardrail.reason]),status:'SIMULATION_REJECTED',fingerprint:key,orderPlan:plan,guardrail});continue}
    const prepared={id:`pa2-${evaluation.evaluationId}`,symbol:evaluation.symbol,assetType:base.assetType,preparationStatus:'ready',proposedPaperTrade:proposedTrade,guardrailEvaluation:{guardrailApproved:true},tradeGuardrailReference:{eventType:guardrail.eventType},buyingPowerValidation:{requiredCapital:guardrail.metrics.marginRequirement,buyingPower:guardrail.metrics.buyingPower},portfolioHeatValidation:{portfolioHeatAfterTrade:guardrail.metrics.portfolioHeatAfterTrade,maxPortfolioHeatPct:guardrail.metrics.maxPortfolioHeatPct},sourceDecisionReference:{id:evaluation.evaluationId,status:'approved'}}
    const execution=simulateRealtimePaperExecution({preparedTrades:[prepared],portfolio,quote:{last:base.price,bid:base.price,ask:base.price,timestamp:evaluation.evaluatedAt},paperTrading:true,liveOrders:false,brokerExecution:false},{emitEvent:false,timestamp:now}); const item=execution.realtimeSimulatedExecutions[0]
    const position=item?.accountingUpdate?.positions?.find(value=>value.symbol===evaluation.symbol)
    results.push({evaluationId:evaluation.evaluationId,candidateId:evaluation.candidateId,symbol:evaluation.symbol,strategyId:evaluation.strategyId,evaluationEvidenceFingerprint:evaluation.evidenceFingerprint??null,status:item?.executionLifecycleStatus==='simulated'?'SIMULATED_FILLED':'SIMULATION_REJECTED',fingerprint:key,orderPlan:plan,tradeQuality:evaluation.tradeQuality??null,regime:evaluation.regime??null,evaluationStatus:evaluation.status,guardrail:{approved:true,checks:guardrail.checks},simulation:{executionStatus:item?.executionLifecycleStatus,fillStatus:item?.executionSimulation?.finalStatus,accountingStatus:item?.accountingUpdate?.status,journalStatus:item?.journalRecord?.journalStatus,realizedPnl:Number.isFinite(Number(item?.journalRecord?.realizedPnl))?Number(item.journalRecord.realizedPnl):null},executionFill:item?.executionSimulation?.fill?{...item.executionSimulation.fill}:null,journal:item?.journalRecord?{tradeId:item.journalRecord.tradeId,journalStatus:item.journalRecord.journalStatus,realizedPnl:item.journalRecord.realizedPnl,decisionGate:item.journalRecord.decisionGate}:null,positionSnapshot:position?{positionId:`paper-position-${key.slice(0,24)}`,symbol:position.symbol,assetType:position.assetType,side:position.side,quantity:position.quantity,averagePrice:position.averagePrice,currentPrice:position.currentPrice,realizedPnl:position.realizedPnl??0,originatingCandidateId:evaluation.candidateId,originatingEvaluationId:evaluation.evaluationId,strategyId:evaluation.strategyId}:null,accountSnapshot:item?.accountingUpdate?.account??null,simulatedAt:now,paperTradingOnly:true,liveOrders:false,brokerExecution:false,automaticExecution:false,engineVersion:PAPER_SIMULATION_VERSION})
  }
  return {status:results.some(r=>r.status==='SIMULATED_FILLED')?'COMPLETE':results.length?'CAUTION':'EMPTY',killSwitchEnabled:true,cycleLimit:config.cycleLimit,dailyLimit:config.dailyLimit,dailyRemaining:Math.max(0,remaining-results.filter(r=>r.status==='SIMULATED_FILLED').length),results,paperTradingOnly:true,automaticExecution:false}
}
